### ISSUE TITLE
Searching for program

### ISSUE THREAD

**Issue by Cletip** [wbolster/emacs-python-black#10]
Hello, I use Anaconda for black. So black is under : 
~/anaconda3/bin/black

So when I use pthyon-black, I have this error : 
Searching for program: No such file or folder, black

I may have missed something else, but thanks for your answers ^^

**Comment by wbolster** [comment]
you need to adapt your search path. please have a look at the readme for one of my other python related emacs packages for inspiration to deal with this exact problem:

 https://github.com/wbolster/emacs-python-pytest
