### ISSUE TITLE
Failed to install python-black

### ISSUE THREAD

**Issue by fpdotmonkey** [wbolster/emacs-python-black#19]
I attempted to install this package as in the README,

```elisp
(use-package python-black
  :demand t
  :after python
  :hook (python-mode . python-black-on-save-mode)) ;; minor change, but not relevant, I assume
```

But I get an error saying it failed,

```
⛔ Error (use-package): Failed to install python-black: https://melpa.org/packages/python-black-20230313.1037.tar: Not found
⛔ Error (use-package): Cannot load python-black
```
This seems to be an older version than the latest that's available on melpa, but I'm not doing anything to request an older version.

I'm also running this as scimax if that makes a difference.

GNU Emacs 29.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2024-05-10

**Comment by wbolster** [comment]
maybe `M-x package-refresh` first?

**Comment by fpdotmonkey** [comment]
Ope, that was it.  I'm dumb, thank you.
