### ISSUE TITLE
Not published on MELPA

### ISSUE THREAD

**Issue by forestbelton** [wbolster/emacs-python-black#2]
Hi,

I found this package today and it seems very useful. However, when I tried to install it, I couldn't find the `python-black` package available on MELPA. I also receive a 404 when I follow the MELPA link from the README.

I'm no Emacs pro, but I don't think this blocks me since I can manually install it. Would it be possible to publish the package to MELPA?

**Comment by 0atman** [comment]
Seconded, was a little surprising to find the package is missing: https://melpa.org/#/python-black

**Comment by LefterisJP** [comment]
Indeed that's strange. In the meantime I made a pr to add it to el-get: https://github.com/dimitri/el-get/pull/2711

**Comment by wbolster** [comment]
sorry all, i had not gotten around to it yet (and  somehow i wasn't watching my own  repo so  only see this now).

PR for melpa at https://github.com/melpa/melpa/pull/6368

**Comment by 0atman** [comment]
Sweet, thank you!

**Comment by wbolster** [comment]
melpa/melpa#6368 was just merged, so `python-black.el` should be available from melpa soon. thanks all for the nudges and your enthusiasm!
