### ISSUE TITLE
Run with `-S, --skip-string-normalization` flag

### ISSUE THREAD

**Issue by jidicula** [wbolster/emacs-python-black#7]
This is a pretty nice package that has faster execution than [blacken](https://github.com/pythonic-emacs/blacken)! I especially like that it's still being actively developed 😉 

I'm trying to set some project-specific Black configs without using a pyproject.toml, so naturally I'd like to use .dir-locals.el. Specifically, I want to skip string normalization in some projects by running `black -S`. How can I do this with this package? I already tried setting `python-black-command` to `"black -S"` in .dir-locals.el, but this didn't seem to do it. Neither did setting `python-black-extra-args` to `"-S"`. The following block is my .dir-locals.el and I tried toggling each of the lines.

```lisp
(
 (python-black-command . "black -S")
 ;; (python-black-extra-args . "-S")
 )
```

Is this a configuration that's possible with this package, or am I misusing these variables?

**Comment by wbolster** [comment]
the extra args variable seems the right place. it should be a list of strings, not a single string, though: `'("-S")`

**Comment by jidicula** [comment]
My .dir-locals.el looks like this now:

```lisp
(
 (python-black-extra-args . '("-S"))
 )

```

but this didn't result in the expected change, and the package's autoformatting still normalizes strings 😦.

However, when I execute `(setq python-black-extra-args '("-S"))`, the autoformatting doesn't normalize strings as expected...

**Comment by jidicula** [comment]
Never mind, I got it to work with the following .dir-locals.el 🎉 

```lisp
(
 (python-mode . (
		 (python-black-extra-args . ("-S"))
		 )
	      )
 )
```
